---
title: "main"
author: "Erim Celen & Rafal"
date: "6/15/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
```

```{r include=FALSE}
library(readr)
library(tidyverse)
library(xts)
library(fUnitRoots)
library(kableExtra)
library(vars)
```

# 1. Abstract
# 2. Aim of the study
# 3. Data Description

```{r include=FALSE}
data <- read.csv("data/data.csv")
```

```{r echo=FALSE}
kable(head(data),'simple',caption = 'Head of Data')
```

# 4. Model building.

```{r}
cor(data[,-1]) %>% kable('simple')
```

```{r}
data$date <- as.Date(data$date, format = "%Y-%m-%d")
data <- xts(data[, -1], order.by = data$date)
```

```{r echo=FALSE}
head(data)
```

```{r}
data[, c(4,10)] %>% 
  as_tibble() %>%
  mutate(date = index(data)) %>%
  pivot_longer(!date) %>%
  ggplot(aes(date, value, col = name)) +
  geom_line() +
  theme_bw() +
  labs(
    title = "y4 and y10 indices"
  )
```

```{r}
source("functions/testdf.R")
```


```{r}
y4_y10 <- data[,c(4,10)]
```

## ADF test for stationarty

```{r}
resultsy4 <-
testdf(variable = y4_y10$y4,  
       max.augmentations = 3)           

resultsy10 <-
testdf(variable = y4_y10$y10,  
       max.augmentations = 3)           

p_values <- cbind(resultsy10,resultsy4)
p_values <- p_values[,c(1,3,8)]
colnames(p_values) <- c("augmentations","p_adf_y10","p_adf_y4")

p_values %>%
  knitr::kable(digits = 3) %>%
  kableExtra::kable_styling(full_width = F,
                            bootstrap_options = c("striped"))

# Both series are non stationary
```

let's see the first differences
```{r}
results2y4 <-
testdf(variable = diff.xts(y4_y10$y4),  
       max.augmentations = 3)           

results2y10 <-
testdf(variable = diff.xts(y4_y10$y10),  
       max.augmentations = 3)           

p_values2 <- cbind(results2y10,results2y4)
p_values2 <- p_values2[,c(1,3,8)]
colnames(p_values2) <- c("augmentations","p_adf_y10","p_adf_y4")

p_values2 %>%
  knitr::kable(digits = 3) %>%
  kableExtra::kable_styling(full_width = F,
                            bootstrap_options = c("striped"))

# Both series are stationary in the first order
```

creating the in sample out sample.

```{r}
in_sample <- y4_y10[1:290] 
out_of_sample <-y4_y10[291:nrow(y4_y10)]
```

## Cointegration test
```{r}
#model for cointegration
model.coint <- lm(y4 ~ y10, data = in_sample) 
summary(model.coint)
```
# buraya cointregration vektoru ve denklemi gelicek.


```{r message=FALSE, warning=FALSE}
#Adf test for residuals.
kable(testdf(variable = residuals(model.coint), max.augmentations = 3))
#y4 and y10 are non-stationary and cointegrated. 
```


## Causality test

```{r}
grangertest(y4 ~ y10,
            data = y4_y10,
            order = 3)
```


```{r}
grangertest(y10 ~ y4,
            data = y4_y10,
            order = 3)
```

 

## VAR Model

```{r}
VARselect(y4_y10, 
          lag.max = 6)    
```

```{r}
VARselect(y4_y10, 
          lag.max = 6,
          season = 12)    
```

```{r}
varseason <- VAR(y4_y10,
                    p = 3, 
                    season = 12)

summary(varseason)
```

```{r}
varlag3 <- VAR(y4_y10, p=3)

summary(varlag3)
```

```{r message=FALSE, warning=FALSE}
plot(varlag3)
```

```{r}
serial.test(varlag3, type = "BG")
#no autocorrelation among residuals.
```

## Forecasting with VAR
```{r}
y4_y10.short <- VAR(in_sample, 
                          p = 3)
```

Now, let's and run the forecasts:
```{r}
y4_y10.forecast <- predict(y4_y10.short,
                                 n.ahead = 10,
                                 ci = 0.95) # 95% confidence interval
```



## ARIMA Model






# 5. Results







